# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA/xianyu/hs_da_ad/hs_da_ad.srcs/sources_1/ip/rom_sanjiao/rom_sanjiao.xci
# IP: The module: 'rom_sanjiao' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/xianyu/hs_da_ad/hs_da_ad.srcs/sources_1/ip/rom_sanjiao/rom_sanjiao_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_sanjiao'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/FPGA/xianyu/hs_da_ad/hs_da_ad.srcs/sources_1/ip/rom_sanjiao/rom_sanjiao.xci
# IP: The module: 'rom_sanjiao' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/xianyu/hs_da_ad/hs_da_ad.srcs/sources_1/ip/rom_sanjiao/rom_sanjiao_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_sanjiao'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
