webtalk_init -webtalk_dir E:/FPGA/xianyu/hs_da_ad/hs_da_ad.sim/sim_1/behav/xsim/xsim.dir/tb_hs_da_ad_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jan 26 16:03:36 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f5e650b7-ec73-4e76-b1c8-dc11f0225227" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ddf3a0ed3f1e4f39b70eacac57ede126" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "40 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "12.67_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15952_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2987658579 -regid "" -xml E:/FPGA/xianyu/hs_da_ad/hs_da_ad.sim/sim_1/behav/xsim/xsim.dir/tb_hs_da_ad_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/FPGA/xianyu/hs_da_ad/hs_da_ad.sim/sim_1/behav/xsim/xsim.dir/tb_hs_da_ad_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/FPGA/xianyu/hs_da_ad/hs_da_ad.sim/sim_1/behav/xsim/xsim.dir/tb_hs_da_ad_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
